CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sequence_number INTEGER NOT NULL,
    type VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL,
    queue_cycle INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    called_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_tickets
        PRIMARY KEY (id),

    CONSTRAINT uk_tickets_type_sequence_queue_cycle
        UNIQUE (type, sequence_number, queue_cycle),

    CONSTRAINT ck_tickets_sequence_number_positive
        CHECK (sequence_number > 0),

    CONSTRAINT ck_tickets_queue_cycle_positive
        CHECK (queue_cycle > 0),

    CONSTRAINT ck_tickets_type
        CHECK (type IN ('NORMAL', 'PREFERRED')),

    CONSTRAINT ck_tickets_status
        CHECK (status IN ('WAITING', 'CALLED'))
    );

CREATE TABLE queue_state (
    id BIGINT NOT NULL,
    normal_sequence INTEGER NOT NULL,
    preferred_sequence INTEGER NOT NULL,
    cycle INTEGER NOT NULL,

    CONSTRAINT pk_queue_state
        PRIMARY KEY (id),

    CONSTRAINT ck_queue_state_single_record
        CHECK (id = 1),

    CONSTRAINT ck_queue_state_normal_sequence_not_negative
        CHECK (normal_sequence >= 0),

    CONSTRAINT ck_queue_state_preferred_sequence_not_negative
        CHECK (preferred_sequence >= 0),

    CONSTRAINT ck_queue_state_cycle_positive
        CHECK (cycle > 0)
    );

INSERT INTO queue_state (
    id,
    normal_sequence,
    preferred_sequence,
    cycle
) VALUES (
    1,
    0,
    0,
    1
);